name: Docker CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: davilucena/volume-image-id:latest
      - name: Set Image ID Output
        run: |
          echo "IMAGE_ID=$(docker images -q davilucena/volume-image-id:latest)" >> $GITHUB_ENV

  publish:
    build-container:
      name: Build docker container image
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Push Docker Image
          uses: docker/build-push-action@v2
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            respository: ${{ github.repository }}/next
            tags: latest, ${{ github.run_number }}
        - name: Publish to Docker Hub
          uses: docker/build-push-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: davilucena222/next